In [1]:
import numpy as np

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:
np.zeros((3,4), dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [9]:
np.zeros((3,4), dtype=str)

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [11]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [14]:
np.random.random(size=(2,4))

array([[0.41462623, 0.95976584, 0.02621333, 0.08383948],
       [0.20173511, 0.92569195, 0.55333963, 0.6773275 ]])

In [15]:
np.random.seed(0) # Генерация псевдо случайных чисел
np.random.random(size=(2,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ]])

In [17]:
np.random.randint(low=0,high=10)

8

In [18]:
np.random.randint(low=0,high=10,size=(2,4))

array([[1, 6, 7, 7],
       [8, 1, 5, 9]])

In [19]:
np.random.uniform(size=(2,4))

array([[0.07103606, 0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834, 0.79915856]])

In [26]:
np.random.seed(0)
np.random.uniform(low=0,high=10,size=(2,4)) # отличие от np.random.random что можна указать диапозон

array([[5.48813504, 7.15189366, 6.02763376, 5.44883183],
       [4.23654799, 6.45894113, 4.37587211, 8.91773001]])

In [29]:
np.random.seed(0)
np.random.choice(np.array([1,2,3]),size=20)

array([1, 2, 1, 2, 2, 3, 1, 3, 1, 1, 1, 3, 2, 3, 3, 1, 2, 2, 2, 2])

In [30]:
np.random.choice(np.array([1,2,3]),size=100)

array([1, 2, 1, 1, 2, 3, 1, 3, 1, 2, 2, 3, 1, 2, 2, 2, 1, 3, 1, 3, 3, 1,
       3, 1, 1, 1, 2, 2, 3, 1, 1, 2, 1, 2, 3, 3, 1, 2, 2, 2, 2, 3, 3, 3,
       1, 3, 2, 1, 2, 3, 1, 1, 3, 1, 1, 1, 1, 1, 1, 3, 1, 3, 2, 2, 2, 1,
       2, 2, 2, 1, 2, 3, 1, 2, 3, 1, 3, 1, 2, 3, 3, 2, 1, 2, 2, 1, 3, 3,
       3, 3, 2, 3, 3, 3, 3, 3, 1, 2, 3, 3])

In [31]:
np.random.choice(np.array(['a','b','c']),size=20)

array(['b', 'c', 'b', 'a', 'c', 'c', 'a', 'c', 'a', 'a', 'c', 'a', 'c',
       'c', 'c', 'a', 'a', 'a', 'b', 'c'], dtype='<U1')