In [1]:
import numpy as np

In [15]:
np.arange(start=1,stop=10, dtype=int) # Всегда одномерные массивы

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(start=1,stop=5, dtype=float,step=1)

array([1., 2., 3., 4.])

In [17]:
np.arange(start=-15,stop=15, dtype=int,step=5)

array([-15, -10,  -5,   0,   5,  10])

In [18]:
np.arange(stop=20).reshape([2,10]) # позволяет модернизировать одномерный массив в двух мерный в примере

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [19]:
np.arange(stop=30).reshape([3,10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [21]:
#error = np.arange(stop=20).reshape([3,10]) # мы пытаемся созадть трехмерный массив, но с 20 елементами, зная математику это не возможно

In [23]:
np.arange(stop=20).reshape([4,5]) # 4 ряда 5 столбцов

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
np.arange(stop=20).reshape([2,2,5]) # 2 ряда по оси 0, в каждом 2 ряда и 5 столбцов

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [25]:
np.arange(stop=20).reshape([4,5]).reshape([2,2,5])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [26]:
np.random.random((10,))

array([0.80403726, 0.28287001, 0.83671848, 0.69853013, 0.56016195,
       0.31739069, 0.38418434, 0.3655065 , 0.30086279, 0.67543246])

In [27]:
np.random.random((10,)).reshape([2,5])

array([[0.94447466, 0.43525871, 0.9903786 , 0.62650378, 0.02412015],
       [0.05222938, 0.94334438, 0.8089158 , 0.51270264, 0.56310365]])

In [32]:
np.random.seed(10)
np.random.randint(50,80,(4,3,3))
np.random.randint(50,80,(4,3,3)).flatten() # Приобразует в одномерный массив

array([72, 63, 55, 63, 69, 75, 63, 78, 72, 75, 62, 51, 75, 54, 77, 68, 79,
       63, 72, 73, 74, 61, 78, 60, 74, 59, 65, 68, 66, 72, 57, 74, 61, 67,
       64, 57])